stages:
    - build
    - deploy
    
build:
    stage: build
    allow_failure: false
    tags: 
        - production
    script:
        - docker build -t bryi/api .
        - docker push bryi/api

deploy:
    image: python:latest
    stage: deploy
    tags: 
        - production
    script:
        - pip install awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set region eu-central-1
        
