version: "3.2"
services:

    api:
        container_name: api
        image: bryi/api:v3
        ports:
            - "5000:5000"
        build:
            context: api/
        environment:
            - PATH=/home/worker/.local/bin:$PATH
            - POSTGRES_URL=10.0.0.114:5432
            - POSTGRES_USER=postgres
            - POSTGRES_PW=
            - POSTGRES_DB=app_redis
            - REDIS_SERVER=10.0.0.114
            - FLASK_APP=api.py
          
    frontend:
        container_name: frontend
        image: bryi/frontend:v3
        build:
            context: web/
        ports:
            - "80:5001"
        depends_on:
            - api
        environment:
            - PATH=/home/worker/.local/bin:$PATH
            - FLASK_APP=flask_frontend.py
    
    rq-worker:
        container_name: rq-worker
        build:
            context: api/
            dockerfile: Dockerfile_worker
        image: bryi/worker:v3
        environment:
            - REDIS_SERVER=10.0.0.114
            - PATH=/home/worker/.local/bin:$PATH
    
