version: "3.2"
services:

    api:
        container_name: api
        image: api
        build:
            context: .
        environment:
            - PATH=/root/.local/bin:$PATH
            - FLASK_APP=api.py
        ports:
            - "5000:5000"
        command: flask run --host=0.0.0.0
          
    frontend:
        container_name: frontend
        image: frontend
        build:
            context: .
        depends_on:
            - api
        environment:
            - PATH=/root/.local/bin:$PATH
            - FLASK_APP=flask_frontend.py 
        ports:
            - "5001:5001"
        command: flask run --port=5001 --host=0.0.0.0

    redis:
        container_name: redis
        image: "redis:alpine"
        command: redis-server
        ports:
            - "6379:6379"
        volumes:
            - /tmp/redis-data:/var/lib/redis
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
    
    rq-worker:
        container_name: rq-worker
        image: api
        environment:
            - PATH=/root/.local/bin:$PATH
        command: rq worker --url redis://redis:6379
