apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.api.containerPort }}
      targetPort: {{ .Values.api.containerPort }}
  selector:
    component: {{ .Values.api.name }}