version: "2.4"
services:

    api:
        image: bryi/api
        mem_limit: 128m
        environment:
            PATH: /home/worker/.local/bin:$PATH
            POSTGRES_URL: database-1.cyy2awpa56jv.eu-central-1.rds.amazonaws.com:5432
            POSTGRES_USER: ctm
            POSTGRES_PW: ctmctmctm
            POSTGRES_DB: app_redis
            REDIS_SERVER: redis.qtpczm.ng.0001.euc1.cache.amazonaws.com
            FLASK_APP: api.py
          
    frontend:
        image: bryi/frontend
        mem_limit: 128m
        links:
            - api
        environment:
            PATH: /home/worker/.local/bin:$PATH
            FLASK_APP: flask_frontend.py

    nginx:
        image: nginx
        volumes:
            - ./nginx:/etc/nginx/templates
        ports:
            - "80:80"
    
    rq-worker:
        image: bryi/worker
        mem_limit: 128m
        environment:
            PATH: /home/worker/.local/bin:$PATH
            REDIS_SERVER: redis.qtpczm.ng.0001.euc1.cache.amazonaws.com