version: "3.2"
services:

    api:
        container_name: api
        image: bryi/api
        build:
            context: api/
        environment:
            - PATH=/home/worker/.local/bin:$PATH
            - POSTGRES_URL=database-1.cyy2awpa56jv.eu-central-1.rds.amazonaws.com:5432
            - POSTGRES_USER=ctm
            - POSTGRES_PW=ctmctmctm
            - POSTGRES_DB=app_redis
            - REDIS_SERVER=redis.qtpczm.ng.0001.euc1.cache.amazonaws.com
            - FLASK_APP=api.py
        expose:
            - "5000"
        entrypoint: ./entrypoint.sh
          
    frontend:
        container_name: frontend
        image: bryi/frontend
        build:
            context: web/
        depends_on:
            - api
        environment:
            - PATH=/home/worker/.local/bin:$PATH
            - FLASK_APP=flask_frontend.py
        ports:
            - "80:5001"
        command: uwsgi --http 0.0.0.0:5001 --module flask_frontend:app
    
    rq-worker:
        container_name: rq-worker
        image: bryi/worker
        environment:
            - PATH=/home/worker/.local/bin:$PATH
            - REDIS_SERVER=redis.qtpczm.ng.0001.euc1.cache.amazonaws.com
        command: rq worker --url redis://$REDIS_SERVER:6379