apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "vpc.amazonaws.com/has-trunk-attached"
              operator: In
              values:
                - "true"
      containers:
        - name: api
          image: bryi/api:v3
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
          - name: POSTGRES_URL
            value: "rds-eksworkshop.cmsyxompjlqg.us-east-1.rds.amazonaws.com:5432"
          - name: POSTGRES_USER
            value: "ctm"
          - name: POSTGRES_PW
            valueFrom:
              secretKeyRef:
                name: ctmpassword
                key: password
          - name: POSTGRES_DB
            value: "app_redis"
          - name: REDIS_SERVER
            value: "redis.ugjdtw.ng.0001.use1.cache.amazonaws.com"
         
