apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: allow-api-access
spec:
  podSelector:
    matchLabels:
      component: api
  securityGroups:
    groupIds:
      - sg-0f207ef62d86d806e