apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: allow-client-access
spec:
  podSelector:
    matchLabels:
      component: web
  securityGroups:
    groupIds:
      - sg-0022f825c5674e621