apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "vpc.amazonaws.com/has-trunk-attached"
              operator: In
              values:
                - "true"
      containers:
        - name: worker
          image: bryi/worker
          env:
          - name: PATH
            value: "/home/worker/.local/bin:$PATH"
          - name: REDIS_SERVER
            value: "redis.ugjdtw.ng.0001.use1.cache.amazonaws.com"
         
