version: 'latest'
namespace: web-fibonacci
app_name: web-fibonacci
enable_ingress: false
env:
  POSTGRES_URL: rds-eksworkshop.cmsyxompjlqg.us-east-1.rds.amazonaws.com:5432
  POSTGRES_USER: ctm
  POSTGRES_PW: ctmpassword
  POSTGRES_DB: app_redis
  REDIS_SERVER: redis.ugjdtw.ng.0001.use1.cache.amazonaws.com
  PATH: /home/worker/.local/bin:$PATH
api:
  name: api
  image: bryi/api:v3
  replicas: 1
  containerPort: 5000
frontend:
  name: web
  image: bryi/frontend:v3
  replicas: 1
  containerPort: 5001
  targetPort: 80
worker:
  name: worker
  image: bryi/worker:v3
  replicas: 6