version: 'latest'
namespace: web-fibonacci
app_name: web-fibonacci
env:
  POSTGRES_URL: 10.0.0.114:5432
  POSTGRES_USER: postgres
  POSTGRES_PW: ctmpassword
  POSTGRES_DB: app_redis
  REDIS_SERVER: 10.0.0.114
  PATH: /home/worker/.local/bin:$PATH
api:
  name: api
  image: bryi/api:v3
  replicas: 1
  containerPort: 5000
frontend:
  name: web
  image: bryi/frontend:v3
  replicas: 1
  containerPort: 5001
  targetPort: 80
worker:
  name: worker
  image: bryi/worker:v3
  replicas: 6